apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::961316944040:user/gh_user
      username: gh_user
      groups:
        - system:masters
